//! Generated id constants for gem `azoth.gamedata`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:c7ca5db24b2715473db1f7125327c1be75f5696e561739dad4387a81644021d2

use az_gem_contract::GemId;

/// `azoth.gamedata`
pub const GEM: GemId = GemId::new("azoth.gamedata");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `authoring`
    pub const AUTHORING: ContributionId = ContributionId::new("authoring");

    /// `builders`
    pub const BUILDERS: ContributionId = ContributionId::new("builders");
}

/// Capability ids declared by `gem.toml`.
pub mod capabilities {
    use az_gem_contract::CapabilityId;

    /// `authoring`
    pub const AUTHORING: CapabilityId = CapabilityId::new("authoring");
}
