[package]
license.workspace = true
repository.workspace = true
name = "texture-atlas"
version = "0.1.0"
edition.workspace = true
description = "Streaming parser for Lumberyard TextureAtlas index assets"


[lints]
workspace = true
[dependencies]
bevy_math = { workspace = true }
quick-xml = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
