//! Generated id constants for gem `azoth.auth`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:7fc301392e86eb54b4162dcc748c607eb65b4f16f6e1ed585a88fba4df8ce189

use az_gem_contract::GemId;

/// `azoth.auth`
pub const GEM: GemId = GemId::new("azoth.auth");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `contract`
    pub const CONTRACT: ContributionId = ContributionId::new("contract");

    /// `host`
    pub const HOST: ContributionId = ContributionId::new("host");
}

/// Capability ids declared by `gem.toml`.
pub mod capabilities {
    use az_gem_contract::CapabilityId;

    /// `contract`
    pub const CONTRACT: CapabilityId = CapabilityId::new("contract");

    /// `host`
    pub const HOST: CapabilityId = CapabilityId::new("host");
}
