//! Stands in for `az_graph_builder::write_generated_rust_graph_source_module`.
//!
//! The real emitter projects whatever the graph compiler wrote beneath the
//! project's `derived/graphs` root; here there is no project and no compiler,
//! so this writes one compiled product and the projection that `include!`s it
//! — in the emitter's own output shape, pinned by
//! `generated_rust_source_module_accepts_an_empty_projection` and its siblings
//! in `az-graph-builder`. Depending on the emitter itself would drag the whole
//! asset-builder stack into a proc-macro crate's dev tree for one file's worth
//! of text.
//!
//! What the fixture is actually for is the other half: nothing below writes a
//! registration call, and `#[contribution]` still composes the graph, because
//! `products = ["graphs"]` in `gem.toml` is the declaration and the expansion
//! is what cashes it.

use std::path::PathBuf;

/// The file name `#[contribution]` includes out of `OUT_DIR`.
/// `az_graph_builder::GENERATED_RUST_GRAPH_SOURCE_MODULE_FILE` is the same
/// name in the crate that owns the emitter.
const MODULE: &str = "azoth_generated_graphs.rs";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));

    let product = out_dir.join("graph.rs");
    std::fs::write(
        &product,
        "\
pub const REGISTRATION: az_graph_runtime::AotGraphRuntimeRegistration =
    az_graph_runtime::AotGraphRuntimeRegistration::new(
        \"az-gem-mount-graphs\",
        \"mount_graph\",
        \"azoth.mount.graph\",
        \"()\",
        mount_graph,
    );

fn mount_graph(
    _ctx: az_graph_runtime::AotGraphExecuteContext<'_>,
) -> Result<(), az_graph_runtime::AotGraphExecutionError> {
    Ok(())
}
",
    )
    .expect("the fixture product is writable");

    let module = format!(
        "\
// @generated by az-graph-builder. Do not edit by hand.

pub mod graph0 {{
    include!({:?});
}}

/// Register every AOT graph compiled into this crate.
///
/// Generated, so a gem cannot ship compiled graphs and forget to register
/// them: the contribution's `register` body calls this and the list below is
/// the build's own answer to what was compiled.
pub fn register<D>(ctx: &mut az_gem_contract::GemContext<'_, D>) {{
    ctx.registrar::<az_graph_runtime::AotGraphRuntimeRegistration>()
        .register_many([
            graph0::REGISTRATION,
        ]);
}}
",
        product.to_string_lossy().as_ref()
    );
    std::fs::write(out_dir.join(MODULE), module).expect("the fixture projection is writable");
}
