//! Generated id constants for gem `azoth.roads-and-rivers`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:47142ffb9827d8f54ea64f598227e9e806232ec32de7fb22c9148ae5830f3360

use az_gem_contract::GemId;

/// `azoth.roads-and-rivers`
pub const GEM: GemId = GemId::new("azoth.roads-and-rivers");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");

    /// `prefab-types`
    pub const PREFAB_TYPES: ContributionId = ContributionId::new("prefab-types");
}
