//! Generated id constants for gem `azoth.vegetation`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:f249efdc1b9da4e06cd8b6467eab2e7004db69b1b089bc3cfcd409fe988de815

use az_gem_contract::GemId;

/// `azoth.vegetation`
pub const GEM: GemId = GemId::new("azoth.vegetation");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");

    /// `prefab-types`
    pub const PREFAB_TYPES: ContributionId = ContributionId::new("prefab-types");
}
