//! Generated id constants for gem `azoth.audio-system`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:553e650b7eb05e2618556cb25ca712145ba7f45bc2fa8d5fc62ea5ed79647eae

use az_gem_contract::GemId;

/// `azoth.audio-system`
pub const GEM: GemId = GemId::new("azoth.audio-system");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");
}
