//! Generated id constants for gem `azoth.legacy-terrain`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:8c6ceb01ab8f6b42f3e4d115b14f5cb512322a13d9c23951407a82bb11398eae

use az_gem_contract::GemId;

/// `azoth.legacy-terrain`
pub const GEM: GemId = GemId::new("azoth.legacy-terrain");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");
}
