//! Generated id constants for engine `azoth`.
//!
//! Generated by `azoth gem ids --engine` from `engine.toml` — do not edit by hand.
//! fingerprint: blake3:097d8d382cc45a5d7e02f583646f030d28ae4c8b1ad5c3746c4f45f339a0cb82

use az_gem_contract::GemId;

/// `azoth`
pub const ENGINE: GemId = GemId::new("azoth");

/// Contribution ids declared by `engine.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `assets`
    pub const ASSETS: ContributionId = ContributionId::new("assets");

    /// `builders`
    pub const BUILDERS: ContributionId = ContributionId::new("builders");

    /// `runtime`
    pub const RUNTIME: ContributionId = ContributionId::new("runtime");

    /// `types`
    pub const TYPES: ContributionId = ContributionId::new("types");
}
