[package]
license.workspace = true
repository.workspace = true
name = "az-gem-camera"
version = "0.1.0"
edition = "2024"
description = "Lumberyard Camera Gem component data as a Bevy plugin"


[lints]
workspace = true
[dependencies]
az-gem-contract = { workspace = true }
bevy = { workspace = true, features = ["default_app", "common_api"] }
thiserror = { workspace = true }
uuid = { workspace = true }
