//! Generated id constants for gem `azoth.lyshine`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:03f5394c943cf59b609124692c624770fe1e7f44d9ad6228f5c429d1bb83f737

use az_gem_contract::GemId;

/// `azoth.lyshine`
pub const GEM: GemId = GemId::new("azoth.lyshine");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `builders`
    pub const BUILDERS: ContributionId = ContributionId::new("builders");

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");
}
