//! Generated id constants for gem `azoth.animation`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:74be1973994691b4d037c75938e2c45259ae4d09ed7dda0e7f08838ffb411f7f

use az_gem_contract::GemId;

/// `azoth.animation`
pub const GEM: GemId = GemId::new("azoth.animation");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");
}
