//! Polymorphic value field codec — `shared_ptr<Base>` on the wire.
//!
//! In the AZ runtime, fields whose static type is a base class can hold any
//! reflected derived class at runtime. The write path emits the runtime
//! type's UUID (or compact `typeIndex`) followed by the type's body bytes; the
//! read path reverses it and dispatches through the registered class handler.
//!
//! Vanilla Lumberyard does the same dispatch (it's what `SerializeContext` /
//! the native type registry does for `AZStd::any`-shaped fields), but on the wire it
//! always emits the full 16-byte UUID. The compact `typeIndex` layer is the
//! only protocol extension this module needs to model.
//!
//! # Design split
//!
//! - [`NetworkBase`] — implemented once per C++ base class (the family of
//!   types that can appear in this slot). The implementor declares the
//!   variants' UUIDs in [`NetworkBase::VARIANTS`]; the default
//!   [`NetworkBase::unmarshal_body`] dispatches against that table without
//!   touching [`TypeRegistry`]. An `Unknown { uuid, body: Vec<u8> }`
//!   variant keeps the wire round-trippable for derived classes we haven't
//!   decoded yet.
//! - [`NetworkValue<T>`] — the field type messages put in their structs.
//!   Implements [`Marshaler`]; consults the buffer's bound [`TypeRegistry`]
//!   only on the read path, to resolve an unknown wire `typeIndex` to a UUID.

use uuid::Uuid;

use crate::az::TypeRegistry;
use crate::serialize::{Marshaler, MarshalerError, ReadBuffer, VlqU32Marshaler, WriteBuffer};

/// One row in a [`NetworkBase`]'s variant dispatch table.
///
/// Carries the variant's AZ UUID, its native `typeIndex`, and an
/// unmarshaler that consumes the body bytes following the UUID/index prefix.
/// The function pointer is the Rust equivalent of the `handler.Unmarshal`
/// vtable slot in native `ClassDesc`.
///
/// `type_index` lets [`NetworkValue<T>::unmarshal`] dispatch directly off
/// the wire integer when it's compressed, skipping the [`TypeRegistry`]
/// lookup entirely. `0` means "this variant has
/// no compact native type id" (e.g. ad-hoc test types) — the
/// runtime falls back to UUID-based dispatch in that case.
///
/// Native runtime validation confirms that the wire-compression key is the
/// sparse `typeIndex`, not the dense registry index.
pub struct VariantEntry<T> {
    pub uuid: Uuid,
    pub type_index: u32,
    pub unmarshal: fn(&mut ReadBuffer) -> Result<T, MarshalerError>,
}

/// Per-base-class polymorphic dispatch.
///
/// One impl per C++ base class that appears as a polymorphic value on the
/// wire. Normally generated by `#[derive(NetworkBase)]` on a closed enum
/// whose variants are the known concrete derived classes; an
/// `Unknown { uuid, body: Vec<u8> }` variant captures derived classes we
/// haven't decoded yet.
///
/// **C++ analog:** AZ dispatches through `ClassDesc::handler.Unmarshal` on a
/// heap-allocated handler object; Rust uses a closed slice.
pub trait NetworkBase: Sized + 'static {
    /// Static dispatch table for known variants. The default
    /// [`unmarshal_body`](Self::unmarshal_body) walks this slice; the
    /// derive macro populates it from each variant's
    /// [`AzTypeInfo::TYPE_ID`](az_core::type_info::AzTypeInfo::TYPE_ID).
    const VARIANTS: &'static [VariantEntry<Self>];

    /// UUID of the variant currently held.
    fn uuid(&self) -> Uuid;

    /// Body bytes for the variant. Mirrors `ClassDesc::handler.Marshal` —
    /// it does **not** include the UUID/index prefix; that's owned by
    /// [`NetworkValue`].
    fn marshal_body(&self, wb: &mut WriteBuffer);

    /// Construct the matching variant by reading its body bytes.
    ///
    /// The default impl looks `uuid` up in [`Self::VARIANTS`] and dispatches
    /// to the matching unmarshaler. Override to handle "unknown" variants
    /// — typically by reading the remainder of the buffer into a
    /// `Vec<u8>` and constructing the family enum's `Unknown` variant.
    ///
    /// # Errors
    ///
    /// Returns whatever the matching [`VariantEntry::unmarshal`] returns for a
    /// malformed body (typically [`MarshalerError::BufferUnderrun`]). When
    /// `uuid` matches no entry in [`Self::VARIANTS`], returns whatever
    /// [`Self::unmarshal_unknown`] returns — [`MarshalerError::UnknownClassUuid`]
    /// for the default impl.
    fn unmarshal_body(uuid: Uuid, rb: &mut ReadBuffer) -> Result<Self, MarshalerError> {
        for entry in Self::VARIANTS {
            if entry.uuid == uuid {
                return (entry.unmarshal)(rb);
            }
        }
        Self::unmarshal_unknown(uuid, rb)
    }

    /// Hook for handling UUIDs not in [`Self::VARIANTS`].
    ///
    /// The default rejects, which is the safe choice for a closed
    /// enum. `#[derive(NetworkBase)]` overrides this to capture the
    /// remaining body into the user's `#[network_base(unknown)]` variant.
    ///
    /// # Errors
    ///
    /// The default impl always returns [`MarshalerError::UnknownClassUuid`] —
    /// a closed enum has no variant to put the body in. An override that
    /// captures unknown bodies may instead return
    /// [`MarshalerError::BufferUnderrun`] while draining `rb`.
    fn unmarshal_unknown(uuid: Uuid, _rb: &mut ReadBuffer) -> Result<Self, MarshalerError> {
        let _ = uuid;
        Err(MarshalerError::UnknownClassUuid)
    }
}

/// A polymorphic-value wire field.
///
/// Wire format:
///
/// ```text
/// VlqU32 type_index
/// if type_index == 0:
///     raw[16] uuid             // "raw UUID follows" sentinel
/// else:
///     uuid = rb.require_types()?.uuid_for_type_index(type_index)
/// body                         // T::marshal_body / T::unmarshal_body
/// ```
///
/// Native runtime validation confirms that nonzero values are sparse compact
/// type indices and zero selects the raw UUID form.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NetworkValue<T: NetworkBase>(pub T);

impl<T: NetworkBase> NetworkValue<T> {
    pub fn into_inner(self) -> T {
        self.0
    }

    pub const fn as_inner(&self) -> &T {
        &self.0
    }
}

impl<T: NetworkBase> From<T> for NetworkValue<T> {
    fn from(value: T) -> Self {
        Self(value)
    }
}

impl<T> Marshaler for NetworkValue<T>
where
    T: NetworkBase,
{
    fn marshal(&self, wb: &mut WriteBuffer) {
        // Mirror the native wire format: emit the per-variant `type_index`
        // when the variant is in the static class table (the compressed
        // form), otherwise fall back to the canonical
        // `type_index = 0 + raw UUID` form. The receiver accepts both
        // forms, so the fallback path is wire-compatible; it's reserved for
        // `Unknown { uuid, body }` variants and ad-hoc test types whose UUID
        // isn't in the native type registry.
        let target_uuid = self.0.uuid();
        let type_index = T::VARIANTS
            .iter()
            .find(|entry| entry.uuid == target_uuid)
            .map_or(0, |entry| entry.type_index);
        if type_index == 0 {
            VlqU32Marshaler.marshal(wb, 0);
            wb.write_bytes(target_uuid.as_bytes());
        } else {
            VlqU32Marshaler.marshal(wb, type_index);
        }
        self.0.marshal_body(wb);
    }

    fn unmarshal(rb: &mut ReadBuffer) -> Result<Self, MarshalerError> {
        let type_index = VlqU32Marshaler.unmarshal(rb)?;
        if type_index == 0 {
            // Wire carried the raw UUID; resolve in-line.
            let raw = rb.read_bytes(16)?;
            let mut bytes = [0u8; 16];
            bytes.copy_from_slice(raw);
            let uuid = Uuid::from_bytes(bytes);
            return Ok(Self(T::unmarshal_body(uuid, rb)?));
        }

        // Fast path: try matching the wire `type_index` against this
        // family's per-T variant table directly. Skips the composed
        // `TypeRegistry` UUID lookup entirely for the common case where the
        // value is a variant we know about — which is also why a buffer with
        // no bound registry still decodes every known variant.
        for entry in T::VARIANTS {
            if entry.type_index == type_index {
                return Ok(Self((entry.unmarshal)(rb)?));
            }
        }

        // Slow path: wire `type_index` is in the static table but isn't a
        // variant of this family. Resolve to UUID and let
        // `unmarshal_unknown` capture it (or reject, for closed enums
        // without an `unknown` variant).
        let uuid = rb
            .require_types()?
            .uuid_for_type_index(type_index)
            .ok_or(MarshalerError::UnknownTypeIndex { type_index })?;
        Ok(Self(T::unmarshal_body(uuid, rb)?))
    }
}

/// Erased ClassDesc-dispatched value.
///
/// Some native fields store a reflected class through a base pointer, but the
/// recovered Rust schema does not always know the concrete base family yet.
/// This carrier still follows the native dispatch path: resolve
/// `StateFragmentTypeId`, run the registered class body unmarshaler, and keep
/// the exact body bytes consumed by that handler.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ClassValue {
    pub uuid: Uuid,
    pub type_index: u32,
    pub body: Vec<u8>,
}

impl ClassValue {
    #[must_use]
    pub fn class_name(&self, types: TypeRegistry<'_>) -> Option<&'static str> {
        types.entry(&self.uuid).map(|entry| entry.name)
    }
}

impl Marshaler for ClassValue {
    fn marshal(&self, wb: &mut WriteBuffer) {
        VlqU32Marshaler.marshal(wb, self.type_index);
        if self.type_index == 0 {
            wb.write_bytes(self.uuid.as_bytes());
        }
        wb.write_bytes(&self.body);
    }

    fn unmarshal(rb: &mut ReadBuffer) -> Result<Self, MarshalerError> {
        let type_index = VlqU32Marshaler.unmarshal(rb)?;
        let types = rb.require_types()?;
        let uuid = if type_index == 0 {
            let raw = rb.read_bytes(16)?;
            let mut bytes = [0u8; 16];
            bytes.copy_from_slice(raw);
            Uuid::from_bytes(bytes)
        } else {
            types
                .uuid_for_type_index(type_index)
                .ok_or(MarshalerError::UnknownTypeIndex { type_index })?
        };

        let desc = types
            .class_desc(&uuid)
            .ok_or(MarshalerError::UnknownClassUuid)?;
        let body_start = rb.position();
        (desc.unmarshal_body)(rb)?;
        let body_end = rb.position();
        let body = rb.range(body_start..body_end)?.to_vec();

        Ok(Self {
            uuid,
            type_index,
            body,
        })
    }
}
