//! Generated id constants for gem `azoth.gradient-signal`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:15dcde7ab0067c99bcceb13821842d6dd7b15e37d1f5ea183d642b4121360587

use az_gem_contract::GemId;

/// `azoth.gradient-signal`
pub const GEM: GemId = GemId::new("azoth.gradient-signal");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");

    /// `prefab-types`
    pub const PREFAB_TYPES: ContributionId = ContributionId::new("prefab-types");
}
