//! Generated id constants for gem `azoth.auth.steam`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:348455329dddfcd0fe548e2a34de9a13158dbeff2e2700f05ceabaeaa02d1b7e

use az_gem_contract::GemId;

/// `azoth.auth.steam`
pub const GEM: GemId = GemId::new("azoth.auth.steam");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `provider`
    pub const PROVIDER: ContributionId = ContributionId::new("provider");
}

/// Capability ids declared by `gem.toml`.
pub mod capabilities {
    use az_gem_contract::CapabilityId;

    /// `provider`
    pub const PROVIDER: CapabilityId = CapabilityId::new("provider");
}
