use std::{future::Future, pin::Pin, sync::Arc};

use crate::{AuthorityTime, ContentDigest, EvidenceSnapshotId, HostChallengeId};

use super::PortableMutationGrantRequest;

/// Unpredictable bytes binding evidence to one fresh challenge.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct HostChallengeNonce([u8; 32]);

impl HostChallengeNonce {
    /// Restores a challenge nonce from cryptographically generated bytes.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Returns the exact challenge bytes.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

/// Construction failure for an immutable host challenge plan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum HostChallengePlanError {
    /// Expiry must follow issuance under the authority clock.
    #[error("host challenge expiry does not follow issuance")]
    InvalidValidityWindow,
}

/// Immutable plan binding one requested grant to fresh verification work.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HostChallengePlan {
    id: HostChallengeId,
    request: PortableMutationGrantRequest,
    nonce: HostChallengeNonce,
    issued_at: AuthorityTime,
    expires_at: AuthorityTime,
}

impl HostChallengePlan {
    /// Creates a fresh challenge plan with a nonempty validity window.
    ///
    /// # Errors
    ///
    /// Rejects expiry at or before issuance.
    pub fn new(
        id: HostChallengeId,
        request: PortableMutationGrantRequest,
        nonce: HostChallengeNonce,
        issued_at: AuthorityTime,
        expires_at: AuthorityTime,
    ) -> Result<Self, HostChallengePlanError> {
        if expires_at <= issued_at {
            return Err(HostChallengePlanError::InvalidValidityWindow);
        }
        Ok(Self {
            id,
            request,
            nonce,
            issued_at,
            expires_at,
        })
    }

    /// Returns the one-time challenge identity.
    #[must_use]
    pub const fn id(&self) -> HostChallengeId {
        self.id
    }

    /// Returns the fresh challenge nonce.
    #[must_use]
    pub const fn nonce(&self) -> HostChallengeNonce {
        self.nonce
    }

    /// Returns the authority-observed issuance time.
    #[must_use]
    pub const fn issued_at(&self) -> AuthorityTime {
        self.issued_at
    }

    /// Returns the authority-observed expiry.
    #[must_use]
    pub const fn expires_at(&self) -> AuthorityTime {
        self.expires_at
    }
}

/// Attributed host response presented for verification.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct HostChallengeSubmission {
    challenge: HostChallengeId,
    nonce: HostChallengeNonce,
    evidence_snapshot: EvidenceSnapshotId,
    evidence_statement: ContentDigest,
}

impl HostChallengeSubmission {
    /// Binds one evidence statement to a challenge and immutable snapshot.
    #[must_use]
    pub const fn new(
        challenge: HostChallengeId,
        nonce: HostChallengeNonce,
        evidence_snapshot: EvidenceSnapshotId,
        evidence_statement: ContentDigest,
    ) -> Self {
        Self {
            challenge,
            nonce,
            evidence_snapshot,
            evidence_statement,
        }
    }

    /// Returns the signed evidence-statement commitment.
    #[must_use]
    pub const fn evidence_statement(self) -> ContentDigest {
        self.evidence_statement
    }
}

/// Closed failures owned by a host-evidence verification adapter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum EvidenceVerificationFailure {
    /// Evidence signature, provenance, or measured result is invalid.
    #[error("host challenge evidence is invalid")]
    InvalidEvidence,
    /// The verifier cannot currently complete its work.
    #[error("host challenge verifier is unavailable")]
    Unavailable,
    /// Verification failed without a narrower public classification.
    #[error("host challenge verification failed")]
    Failed,
}

/// A challenge verifier's asynchronous result.
pub type ChallengeVerificationFuture<'a> =
    Pin<Box<dyn Future<Output = Result<(), EvidenceVerificationFailure>> + Send + 'a>>;

/// Consumer-owned boundary for signatures, provenance, and measured evidence.
pub trait ChallengeVerificationPort: Send + Sync {
    /// Verifies the already boundary-checked plan and submission.
    fn verify<'a>(
        &'a self,
        plan: &'a HostChallengePlan,
        submission: &'a HostChallengeSubmission,
    ) -> ChallengeVerificationFuture<'a>;
}

/// Domain refusal before external evidence verification begins.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum HostChallengeRefusal {
    /// Submission addresses another challenge.
    #[error("host evidence addresses another challenge")]
    WrongChallenge,
    /// Submission did not echo the fresh challenge nonce.
    #[error("host evidence contains the wrong challenge nonce")]
    WrongNonce,
    /// Submission names evidence other than the requested immutable snapshot.
    #[error("host evidence names the wrong evidence snapshot")]
    WrongEvidenceSnapshot,
    /// Challenge is no longer fresh under the authority clock.
    #[error("host challenge expired")]
    Expired,
}

/// Failure to turn a host challenge into a type-proven grant input.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum ChallengeVerificationFailure {
    /// Boundary facts refused the submission before provider work.
    #[error(transparent)]
    Refused(#[from] HostChallengeRefusal),
    /// The evidence verification adapter rejected or could not verify it.
    #[error(transparent)]
    Verification(#[from] EvidenceVerificationFailure),
}

/// Fresh host challenge accepted by the selected evidence verifier.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifiedHostChallenge {
    plan: HostChallengePlan,
}

impl VerifiedHostChallenge {
    /// Returns the exact behavior-specific request proven by this challenge.
    #[must_use]
    pub const fn request(&self) -> &PortableMutationGrantRequest {
        &self.plan.request
    }

    pub(super) const fn into_request(self) -> PortableMutationGrantRequest {
        self.plan.request
    }
}

/// Checks challenge binding and freshness, then verifies evidence externally.
///
/// # Errors
///
/// Refuses mismatched or expired input before calling the verification port,
/// and preserves the adapter's typed verification failure.
pub async fn verify_host_challenge(
    plan: HostChallengePlan,
    submission: HostChallengeSubmission,
    now: AuthorityTime,
    verifier: Arc<dyn ChallengeVerificationPort>,
) -> Result<VerifiedHostChallenge, ChallengeVerificationFailure> {
    if submission.challenge != plan.id {
        return Err(HostChallengeRefusal::WrongChallenge.into());
    }
    if submission.nonce != plan.nonce {
        return Err(HostChallengeRefusal::WrongNonce.into());
    }
    if submission.evidence_snapshot != plan.request.evidence_snapshot() {
        return Err(HostChallengeRefusal::WrongEvidenceSnapshot.into());
    }
    if now >= plan.expires_at {
        return Err(HostChallengeRefusal::Expired.into());
    }
    verifier.verify(&plan, &submission).await?;
    Ok(VerifiedHostChallenge { plan })
}
