//! Generated id constants for gem `azoth.lmbr-central`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:a90c098da4bb399f44357c9f470064541d1987a1dbb95295b6260a51f279c284

use az_gem_contract::GemId;

/// `azoth.lmbr-central`
pub const GEM: GemId = GemId::new("azoth.lmbr-central");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `builders`
    pub const BUILDERS: ContributionId = ContributionId::new("builders");

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");

    /// `prefab-types`
    pub const PREFAB_TYPES: ContributionId = ContributionId::new("prefab-types");
}
