//! Generated id constants for gem `azoth.footsteps`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:6f98ab581e2adc95e19b9c3274c69d2941b39d3dee85ca0bf680ac2a17ab3085

use az_gem_contract::GemId;

/// `azoth.footsteps`
pub const GEM: GemId = GemId::new("azoth.footsteps");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");
}
