[package]
license.workspace = true
repository.workspace = true
name = "lyshine"
version = "0.1.0"
edition.workspace = true
description = "Streaming parsers for LyShine metadata assets"


[lints]
workspace = true
[dependencies]
bevy_color = { workspace = true }
glam = { workspace = true }
quick-xml = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
