[package]
license.workspace = true
repository.workspace = true
name = "az-pak"
version = "0.1.0"
edition.workspace = true


[lints]
workspace = true
[lib]
name = "az_pak"
path = "src/lib.rs"

[features]
default = []
oodle = ["dep:oodle-safe"]

[dependencies]
az-filesystem = { workspace = true }
flate2 = { workspace = true }
humansize = { workspace = true }
memmap2 = { workspace = true }
oodle-safe = { workspace = true, optional = true }
rayon = { workspace = true }
thiserror = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
zip = { workspace = true }

[[bench]]
name = "decompress"
harness = false
