//! Generated id constants for gem `azoth.camera`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:2d1eb1973147577ebcb5e500f57ed76612dbf30dfed035144211c9ac157ad7fe

use az_gem_contract::GemId;

/// `azoth.camera`
pub const GEM: GemId = GemId::new("azoth.camera");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");
}
