//! Generated id constants for gem `azoth.steam`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:411e8f23b03a47896e42c8a9e52c7fa38f75f849999969c6e658b45fb94ff277

use az_gem_contract::GemId;

/// `azoth.steam`
pub const GEM: GemId = GemId::new("azoth.steam");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `client-runtime`
    pub const CLIENT_RUNTIME: ContributionId = ContributionId::new("client-runtime");
}

/// Capability ids declared by `gem.toml`.
pub mod capabilities {
    use az_gem_contract::CapabilityId;

    /// `client-runtime`
    pub const CLIENT_RUNTIME: CapabilityId = CapabilityId::new("client-runtime");
}
