//! Generated id constants for gem `azoth.fast-noise`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:15d141d2525806335e06cfabca82efd415855ced6fb46516e9ad3e96908ea6fa

use az_gem_contract::GemId;

/// `azoth.fast-noise`
pub const GEM: GemId = GemId::new("azoth.fast-noise");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");

    /// `prefab-types`
    pub const PREFAB_TYPES: ContributionId = ContributionId::new("prefab-types");
}
