//! Generated id constants for gem `azoth.nv-cloth`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:8bd5258bd2ab5a9f2c01dea63b9e4391faa6810c732c6a8178e589651fb2946c

use az_gem_contract::GemId;

/// `azoth.nv-cloth`
pub const GEM: GemId = GemId::new("azoth.nv-cloth");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");
}
