//! Generated id constants for gem `azoth.slayer-script`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:979a076cba09bc4ae12e416f379d265f6c2f629873e18c278e431bf42df9390d

use az_gem_contract::GemId;

/// `azoth.slayer-script`
pub const GEM: GemId = GemId::new("azoth.slayer-script");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");

    /// `prefab-types`
    pub const PREFAB_TYPES: ContributionId = ContributionId::new("prefab-types");
}
