//! Generated id constants for gem `azoth.rock-n-roll`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:02576389c83230a2148f838d92273df0455a0bf0b129de2951ac1def60cad2fb

use az_gem_contract::GemId;

/// `azoth.rock-n-roll`
pub const GEM: GemId = GemId::new("azoth.rock-n-roll");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");

    /// `prefab-types`
    pub const PREFAB_TYPES: ContributionId = ContributionId::new("prefab-types");
}
