//! Generated id constants for gem `azoth.eos`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:67cca40cebf224a8312baa718fe49c3ea50f8aebba143b2383d0f4fbd2d76fed

use az_gem_contract::GemId;

/// `azoth.eos`
pub const GEM: GemId = GemId::new("azoth.eos");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `anti-cheat-client`
    pub const ANTI_CHEAT_CLIENT: ContributionId = ContributionId::new("anti-cheat-client");

    /// `client-runtime`
    pub const CLIENT_RUNTIME: ContributionId = ContributionId::new("client-runtime");

    /// `server-runtime`
    pub const SERVER_RUNTIME: ContributionId = ContributionId::new("server-runtime");
}

/// Capability ids declared by `gem.toml`.
pub mod capabilities {
    use az_gem_contract::CapabilityId;

    /// `anti-cheat-client`
    pub const ANTI_CHEAT_CLIENT: CapabilityId = CapabilityId::new("anti-cheat-client");

    /// `anti-cheat-server`
    pub const ANTI_CHEAT_SERVER: CapabilityId = CapabilityId::new("anti-cheat-server");

    /// `client-runtime`
    pub const CLIENT_RUNTIME: CapabilityId = CapabilityId::new("client-runtime");

    /// `server-runtime`
    pub const SERVER_RUNTIME: CapabilityId = CapabilityId::new("server-runtime");
}
