[package]
license.workspace = true
repository.workspace = true
name = "http-plugin"
version = "0.1.0"
edition = "2024"


[lints]
workspace = true
[dependencies]
bevy = { workspace = true, features = ["default_app"] }
reqwest = { workspace = true, default-features = false, features = [
    "json",
    "rustls",
    "http2",
    "query",
    "form",
] }
tokio = { workspace = true, default-features = false, features = [
    "rt",
    "rt-multi-thread",
    "net",
    "io-util",
    "sync",
] }
tracing = { workspace = true }
http = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
logging-registry = { path = "../logging-registry" }
