//! Generated id constants for gem `azoth.auth.eos`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:da4743a3bb16460bb9186656030036323bf31f9d3de0ec34c14a50c90cea065d

use az_gem_contract::GemId;

/// `azoth.auth.eos`
pub const GEM: GemId = GemId::new("azoth.auth.eos");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `provider`
    pub const PROVIDER: ContributionId = ContributionId::new("provider");
}

/// Capability ids declared by `gem.toml`.
pub mod capabilities {
    use az_gem_contract::CapabilityId;

    /// `provider`
    pub const PROVIDER: CapabilityId = CapabilityId::new("provider");
}
