//! Generated id constants for gem `azoth.auth.local`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:867a8fdea79b97bfbbbdfb96df523a1ff377d24176a7d9b5ec5f541a93fbad3b

use az_gem_contract::GemId;

/// `azoth.auth.local`
pub const GEM: GemId = GemId::new("azoth.auth.local");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `provider`
    pub const PROVIDER: ContributionId = ContributionId::new("provider");
}

/// Capability ids declared by `gem.toml`.
pub mod capabilities {
    use az_gem_contract::CapabilityId;

    /// `provider`
    pub const PROVIDER: CapabilityId = CapabilityId::new("provider");
}
