//! Generated id constants for gem `azoth.historical-input`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:0a7bf6f0d38abdb25d97376d7621e47693b131c381c49d45cf823475a8d7b6b7

use az_gem_contract::GemId;

/// `azoth.historical-input`
pub const GEM: GemId = GemId::new("azoth.historical-input");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");
}
