//! Generated id constants for gem `azoth.texture-atlas`.
//!
//! Generated by `azoth gem ids` from `gem.toml` — do not edit by hand.
//! fingerprint: blake3:be139a66668745a4d476c273d963b2a413eb1bca555c11d907281e03c7458072

use az_gem_contract::GemId;

/// `azoth.texture-atlas`
pub const GEM: GemId = GemId::new("azoth.texture-atlas");

/// Contribution ids declared by `gem.toml`.
pub mod contributions {
    use az_gem_contract::ContributionId;

    /// `builders`
    pub const BUILDERS: ContributionId = ContributionId::new("builders");

    /// `package`
    pub const PACKAGE: ContributionId = ContributionId::new("package");
}
